name: Publish to crates.io

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  call-publish:
    uses: qntx/workflows/.github/workflows/rust-publish.yml@main
    with:
      package: "signer-primitives signer-btc signer-evm signer-svm signer-cosmos signer-tron signer-spark signer-fil signer-ton signer-sui signer signer-cli"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
